GET http://localhost:8080/rest/account
Accept: */*
Cache-Control: no-cache
#Authorization: Basic user@gmail.com 123
Authorization: Basic user@gmail.com password
#Authorization: Basic admin@javaops.ru admin

###

PUT http://localhost:8080/rest/account
Content-Type: application/json
Authorization: Basic user@gmail.com password

{
  "email": "user@gmail.com",
  "firstName": "New_First",
  "lastName": "New_Last"
}

###
POST http://localhost:8080/rest/account/register
Content-Type: application/json
#Authorization: Basic user@gmail.com password

{
  "email": "test@test.com",
  "firstName": "Test",
  "lastName": "Test",
  "password": "test"
}

###

GET http://localhost:8080/rest/users
Accept: */*
Cache-Control: no-cache
#Authorization: Basic user@gmail.com 123
#Authorization: Basic user@gmail.com password
Authorization: Basic admin@javaops.ru admin

###

POST http://localhost:8080/rest/users
Content-Type: application/json
#Authorization: Basic user@gmail.com 123
#Authorization: Basic user@gmail.com password
Authorization: Basic admin@javaops.ru admin

{
  "email": "test@test.com",
  "firstName": "Test",
  "lastName": "Test",
  "password": "test",
  "roles": [
    "USER",
    "ADMIN"
  ]
}

###

PUT http://localhost:8080/rest/users/1
Content-Type: application/json
#Authorization: Basic user@gmail.com 123
Authorization: Basic user@gmail.com password
#Authorization: Basic admin@javaops.ru admin

{
  "email": "user@gmail.com",
  "firstName": "Very_New_First",
  "lastName": "New_Last"
}

###


GET http://localhost:8080/rest/restaurants
Accept: */*
Cache-Control: no-cache
#Authorization: Basic user@gmail.com 123
#Authorization: Basic user@gmail.com password
Authorization: Basic admin@javaops.ru admin

###

POST http://localhost:8080/rest/restaurants
Content-Type: application/json
#Authorization: Basic user@gmail.com 123
#Authorization: Basic user@gmail.com password
Authorization: Basic admin@javaops.ru admin

{
  "name": "New restaurant"
}

###

PUT http://localhost:8080/rest/restaurants/1
Content-Type: application/json
#Authorization: Basic user@gmail.com 123
#Authorization: Basic user@gmail.com password
Authorization: Basic admin@javaops.ru admin

{
  "name": "Updated name"
}

###

DELETE http://localhost:8080/rest/restaurants/1
#Authorization: Basic user@gmail.com 123
#Authorization: Basic user@gmail.com password
Authorization: Basic admin@javaops.ru admin

###

GET http://localhost:8080/rest/dishes
Accept: */*
Cache-Control: no-cache
#Authorization: Basic user@gmail.com 123
#Authorization: Basic user@gmail.com password
Authorization: Basic admin@javaops.ru admin

###

POST http://localhost:8080/rest/dishes
Content-Type: application/json
#Authorization: Basic user@gmail.com 123
#Authorization: Basic user@gmail.com password
Authorization: Basic admin@javaops.ru admin

{
  "name": "New dish",
  "price": 1999,
  "restaurant": "http://localhost:8080/rest/restaurant/1"
}

###

PUT http://localhost:8080/rest/dishes/6/restaurant
Content-Type: text/uri-list
#Authorization: Basic user@gmail.com 123
#Authorization: Basic user@gmail.com password
Authorization: Basic admin@javaops.ru admin

http://localhost:8080/rest/restaurants/1

###

GET http://localhost:8080/rest/restaurants/1/lunches
Accept: */*
Cache-Control: no-cache
#Authorization: Basic user@gmail.com 123
#Authorization: Basic user@gmail.com password
Authorization: Basic admin@javaops.ru admin

###
#Set today lunch (bind restaurant resource and a sequence of dish resources
POST http://localhost:8080/rest/lunches
Content-Type: application/json
#Authorization: Basic user@gmail.com 123
#Authorization: Basic user@gmail.com password
Authorization: Basic admin@javaops.ru admin

{
  "restaurant": "http://localhost:8080/rest/restaurant/1",
  "dishes": [
    "http://localhost:8080/rest/dishes/1",
    "http://localhost:8080/rest/dishes/3",
    "http://localhost:8080/rest/dishes/4"
  ]
}

###

DELETE http://localhost:8080/rest/lunches/7
#Authorization: Basic user@gmail.com 123
#Authorization: Basic user@gmail.com password
Authorization: Basic admin@javaops.ru admin

###